### PR TITLE
Implement mutable extension to `scoped_thread_local` macro

### PR DESCRIPTION
**Pull request by Diggsey**
Removes HKT from #12

### CODE REVIEW

**Comment by alexcrichton** [comment]
Personally I don't think it's worth adding this to cover up the fact that it's still basically a `Cell` under the hood. I would personally say that usage of this macro, if mutability is needed, should use `Cell` and `RefCell` to acknowledge that interior mutability is required and recursive lookups can happen.

**Comment by Diggsey** [comment]
@alexcrichton I'm not quite sure what you mean - it's not possible to emulate this macro using Cell or RefCell.

Here's an example: https://github.com/Diggsey/actix-interop/blob/master/src/lib.rs#L15-L26

**Comment by alexcrichton** [comment]
Er sorry, yes, that's true that `Cell` and `RefCell` won't literally work because they would need some form of lifetime (like `Cell<Option<&'a mut T>>`), and that's not possible. I'm not a huge fan though of how this hides the mutability internally and silently takes the item on `with` and puts it back at the end.

TBH though I don't really have much interest in keeping this crate going. I would prefer at this point if it's basically considered frozen and if extensions like this are needed they'd be added in a different crate with a new maintainer.

**Comment by Diggsey** [comment]
That is a shame 😦

**Comment by Diggsey** [comment]
In case anyone else comes across this with the same need, I published the crate [`scoped-tls-hkt`](https://github.com/Diggsey/scoped-tls-hkt).

**Pull request closed without merging**
